// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX3sl8KbyC5N21Ax-1qeW7sWVy1jFnqWc',
    appId: '1:224069501769:web:962eb1789766dbc4021098',
    messagingSenderId: '224069501769',
    projectId: 'secondsight-5cba4',
    authDomain: 'secondsight-5cba4.firebaseapp.com',
    databaseURL: 'https://secondsight-5cba4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'secondsight-5cba4.firebasestorage.app',
    measurementId: 'G-D15TBV1GW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVhlqLw7xqkbyqHoUZ61k1Nr4fVW5p4XY',
    appId: '1:224069501769:android:4f69e8cb4a702024021098',
    messagingSenderId: '224069501769',
    projectId: 'secondsight-5cba4',
    databaseURL: 'https://secondsight-5cba4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'secondsight-5cba4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6FxbNGk-2b7IFwghZUrQEeS0HyzZe3Ik',
    appId: '1:224069501769:ios:ee37e58a3ef41d34021098',
    messagingSenderId: '224069501769',
    projectId: 'secondsight-5cba4',
    databaseURL: 'https://secondsight-5cba4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'secondsight-5cba4.firebasestorage.app',
    iosBundleId: 'edu.tar.my.secondsight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6FxbNGk-2b7IFwghZUrQEeS0HyzZe3Ik',
    appId: '1:224069501769:ios:ee37e58a3ef41d34021098',
    messagingSenderId: '224069501769',
    projectId: 'secondsight-5cba4',
    databaseURL: 'https://secondsight-5cba4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'secondsight-5cba4.firebasestorage.app',
    iosBundleId: 'edu.tar.my.secondsight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX3sl8KbyC5N21Ax-1qeW7sWVy1jFnqWc',
    appId: '1:224069501769:web:b4c441a22ca75866021098',
    messagingSenderId: '224069501769',
    projectId: 'secondsight-5cba4',
    authDomain: 'secondsight-5cba4.firebaseapp.com',
    databaseURL: 'https://secondsight-5cba4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'secondsight-5cba4.firebasestorage.app',
    measurementId: 'G-JMBSLJLNFQ',
  );

}